
# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

require ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/tools.rb'
require 'pathname'

$jobid = ENV['jobid']
$blind = ENV['blind']
# Figure out what run period we are in
$period = '13TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end

samples = Hash[
               "ttbar" => get_sample_names('TT'),
               "singlet" => get_sample_names('ST_tW')+get_sample_names('ST_t-ch'),
               "singletbar" => get_sample_names('Tbar_t'), 
	       "wg"=>get_sample_names('WG'), 
	       "suneath" => get_sample_names('W2JetsToLNu_TuneCUETP8M1_13TeV-madgraph'),
               "wjets" => get_sample_names('W1JetsToLNu_')+get_sample_names('W2JetsToLNu_')+get_sample_names('W3JetsToLNu_')+get_sample_names('W4JetsToLNu_')+get_sample_names('WJetsToLNu_'),
#               "wjets" => get_sample_names('WJetsToLNu_TuneCUETP8M1_13TeV-madgraph'),
               "wwjets" => get_sample_names('WWJets'),
               "wzjets" => get_sample_names('WZJets'),
               "zzjets" => get_sample_names('ZZJets'),
               "zjets" => get_sample_names('jets_M50'),
               "zjets_skimmedLL" => get_sample_names('jets_M50_skimmedLL'),
               "zjets_skimmedTT" => get_sample_names('jets_M50_skimmedTT'),
               "diboson" =>get_sample_names('WW')+get_sample_names('WZ')+get_sample_names('ZZ'),
               "excldiboson"=>get_sample_names('WZTo2L2Q')+get_sample_names('VVTo2L2Nu')+get_sample_names('WWTo1L1Nu2Q')+get_sample_names('WZJToLLLNu')+get_sample_names('WZTo1L1Nu2Q')+get_sample_names('WZTo1L3Nu')+get_sample_names('ZZTo2L2Q')+get_sample_names('ZZTo4L'),
               "extra" => Array['T_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola','Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola','Tbar_t-channel','T_t-channel'],
               "ewk" => Array['Zjets_M50', 
                              'WWJetsTo2L2Nu_TuneZ2_8TeV',
                              'TTJets_FullLeptMGDecays_8TeV-madgraph-tauola','TTJets_SemiLeptMGDecays_8TeV-madgraph-tauola'], 
               # Maria's version
               "DY" => get_sample_names('DYJetsToLL_M-50')+get_sample_names('DY1JetsToLL_M-50')+get_sample_names('DY2JetsToLL_M-50')+get_sample_names('DY3JetsToLL_M-50')+get_sample_names('DY4JetsToLL_M-50'),
               "ZTT" => get_sample_names('ZTauTauJets_M-50')+get_sample_names('ZTauTau1Jets_M-50')+get_sample_names('ZTauTau2Jets_M-50')+get_sample_names('ZTauTau3Jets_M-50')+get_sample_names('ZTauTau4Jets_M-50'),
               "DYlowmass" => get_sample_names('DYJetsToLL_M-10to50')+get_sample_names('DY1JetsToLL_M-10to50')+get_sample_names('DY2JetsToLL_M-10to50')+get_sample_names('DY3JetsToLL_M-10to50')+get_sample_names('DY4JetsToLL_M-10to50'),
               "QCD_mc" => get_sample_names('QCD_Pt-20toInf_MuEnrichedPt15'),
   
	       "DYinclus" => get_sample_names('DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
               "signal200" => get_sample_names('GluGlu_LFV_HToMuTau_M200')+get_sample_names('VBF_LFV_HToMuTau_M200'),
               "signalMCgg" => get_sample_names('GluGlu_LFV_HToETau_M'),
               "signalMCvbf" => get_sample_names('VBF_LFV_HToETau_M'),
               "signalMCggEtau" => get_sample_names('GluGlu_LFV_HToETau_M'),
               "signalMCvbfEtau" => get_sample_names('VBF_LFV_HToETau_M'),
               "officialsignalMCMuTaugg" => get_sample_names('Official_GluGlu_LFV_HToMuTau_M'),
               "signalMCMuTaugg" => get_sample_names('GluGlu_LFV_HToMuTau_M'),
               "signalMCMuTauvbf" => get_sample_names('VBF_LFV_HToMuTau_M'),
	       "htautau" => get_sample_names('HToTauTau') + get_sample_names('ttHJetToTT'),
	       "hww" => get_sample_names('HToWW'),
               "ggHiggsTo2Taus" => get_sample_names('GluGluHToTauTau_M'),
               "vbfHiggsTo2Taus" => get_sample_names('VBFHToTauTau_M'),
               "Zembedded" => get_sample_names('ZetauEmbedded'),
               "dataSingleE" => get_sample_names('data_SingleElectron_Run2015'),
               "dataSingleMu" => get_sample_names('data_SingleMuon_Run2016'),
               "data"=>get_sample_names(' data_SingleMuon_Run2016D'),
               "dataD"=>get_sample_names('data_SingleMuon_Run2016D'),
               "dataC"=>get_sample_names('data_SingleMuon_Run2016C'),
               "dataB"=>get_sample_names('data_SingleMuon_Run2016B'),
               "dataE"=>get_sample_names('data_SingleMuon_Run2016E'),
               "dataF"=>get_sample_names('data_SingleMuon_Run2016F'),
	       "dataG"=>get_sample_names('data_SingleMuon_Run2016G'),
               "dataH"=>get_sample_names('data_SingleMuon_Run2016H')
                              
]



# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end
def get_plotter_results(analyzer)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
end

################################################################################
## Recipes to analyze the electronic channel of the LFV HToMuTau analysis
##  targets:
##     me
################################################################################



task :runhighmass => get_analyzer_results("Analyzer_MuE_highmass",samples['signalMCMuTaugg']+samples['signalMCMuTauvbf']+samples['ttbar']+samples['DY']+samples['ggHiggsTo2Taus']+samples['vbfHiggsTo2Taus']+samples['wjets']+samples['wg']+samples['ZTT']+samples['singlet']+samples['dataB']+samples['dataC']+samples['dataD']+samples['dataE']+samples['dataF']+samples['dataG']+samples['dataH']+samples['DYlowmass']+samples['signalMCggEtau']+samples['signalMCvbfEtau']+samples['excldiboson']+samples['hww']+samples['htautau']+samples['QCD_mc'])


task :runhighmass200_pt60 => get_analyzer_results("Analyzer_MuE_highmass_200optimized_Mu50_pt60",samples['QCD_mc'])

task :runhighmass450_Mu50 => get_analyzer_results("Analyzer_MuE_highmass_450optimized_Mu50",samples['QCD_mc'])

task :runhighmass200_pt60_QCDCR => get_analyzer_results("Analyzer_MuE_highmass_200optimized_Mu50_pt60_QCD_CR",samples['signalMCMuTaugg']+samples['ttbar']+samples['DY']+samples['wjets']+samples['wg']+samples['ZTT']+samples['singlet']+samples['dataB']+samples['dataC']+samples['dataD']+samples['dataE']+samples['dataF']+samples['dataG']+samples['dataH']+samples['DYlowmass']+samples['excldiboson']+samples['QCD_mc'])

task :runhighmass450_ttbarCR => get_analyzer_results("Analyzer_MuE_450_ttbarCR",samples['signalMCMuTaugg']+samples['ttbar']+samples['DY']+samples['wjets']+samples['wg']+samples['ZTT']+samples['singlet']+samples['dataB']+samples['dataC']+samples['dataD']+samples['dataE']+samples['dataF']+samples['dataG']+samples['dataH']+samples['DYlowmass']+samples['excldiboson'])

task :runhighmass200_ttbarCR => get_analyzer_results("Analyzer_MuE_200_ttbarCR",samples['signalMCMuTaugg']+samples['ttbar']+samples['DY']+samples['wjets']+samples['wg']+samples['ZTT']+samples['singlet']+samples['dataB']+samples['dataC']+samples['dataD']+samples['dataE']+samples['dataF']+samples['dataG']+samples['dataH']+samples['DYlowmass']+samples['excldiboson'])


task :runhighmass450_QCDCR => get_analyzer_results("Analyzer_MuE_highmass_450optimized_QCDCR",samples['officialsignalMCMuTaugg']+samples['ttbar']+samples['DY']+samples['ggHiggsTo2Taus']+samples['vbfHiggsTo2Taus']+samples['wjets']+samples['wg']+samples['ZTT']+samples['singlet']+samples['dataB']+samples['dataC']+samples['dataD']+samples['dataE']+samples['dataF']+samples['dataG']+samples['dataH']+samples['DYlowmass']+samples['signalMCggEtau']+samples['signalMCvbfEtau']+samples['excldiboson']+samples['hww']+samples['htautau'])

task :runhighmass200_QCDCR => get_analyzer_results("Analyzer_MuE_highmass_200optimized_QCDCR",samples['officialsignalMCMuTaugg']+samples['ttbar']+samples['DY']+samples['ggHiggsTo2Taus']+samples['vbfHiggsTo2Taus']+samples['wjets']+samples['wg']+samples['ZTT']+samples['singlet']+samples['dataB']+samples['dataC']+samples['dataD']+samples['dataE']+samples['dataF']+samples['dataG']+samples['dataH']+samples['DYlowmass']+samples['signalMCggEtau']+samples['signalMCvbfEtau']+samples['excldiboson']+samples['hww']+samples['htautau'])


task :runBDTtreemaker => get_analyzer_results("LFVHEMuAnalyzerMVAmakeBDTtrees",samples['signalMCMuTaugg']+samples['signalMCMuTauvbf']+samples['ttbar']+samples['DY']+samples['DYlowmass']+samples['signalMCggEtau']+samples['signalMCvbfEtau'])



$etdir = "plots/#{$jobid}/LFVHETauAnalyzer/et/"
directory $etdir 
file  "#{$emtdir}/plot#{$period}.root" do |t|
  sh "echo $jobid"
  sh "python myNewPlotterReco.py" 
  
end


task :drawTauFakeRate => get_plotter_results("plotTauFakeRate.py")

task :drawplots => "#{$emtdir}/plot#{$period}.root"


